#!/usr/bin/env bash


function _on_error()
{(
    set +x
    shource _print_stack()

    local lineno=$1
    shift
    local pipe_fails=( "${@}" )
    echo "ERROR (${pipe_fails[@]}) on line $1: Most recent call last:" >&2
    _print_stack >&2
) }
